name = "Not Another Vanilla Modpack"
author = "fathulfahmy"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb442d876a2a65b628a8fd0ae7f6ad3fcc85bdc49bb903fd5c47f026376d68ad"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
